import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { ParsedTrafficData } from "./csvParser";

export interface ReportMetadata {
  type: string;
  dateRange: string;
  generatedBy: string;
  certifiedBy?: string;
  certifiedAt?: string;
  refNumber?: string;
}

export const generateTrafficReport = (
  data: ParsedTrafficData[],
  metadata: ReportMetadata
) => {
  const doc = new jsPDF() as any;
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(78, 98, 144); // STAP Hub Blue
  doc.text("STAP-HUB TRAFFIC ANALYTICS", 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("SMART TRAFFIC AUTOMATION PROGRAM", 14, 28);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 32, pageWidth - 14, 32);

  // Metadata
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(`Report Type: ${metadata.type}`, 14, 45);
  doc.text(`Date Range: ${metadata.dateRange}`, 14, 52);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, 14, 59);
  doc.text(`Generated By: ${metadata.generatedBy}`, 14, 66);

  if (metadata.refNumber) {
    doc.setFontSize(10);
    doc.text(`Reference No: ${metadata.refNumber}`, pageWidth - 14, 45, { align: "right" });
  }

  // Summary Metrics
  let totalVehicles = 0;
  const vehicleCounts: { [type: string]: number } = {};
  
  data.forEach(p => {
    if (p.finalSummary?.corridorTotals) {
      Object.entries(p.finalSummary.corridorTotals.vehicles).forEach(([type, count]) => {
        vehicleCounts[type] = (vehicleCounts[type] || 0) + (count as number);
      });
      totalVehicles += p.finalSummary.corridorTotals.grandUniqueCount;
    } else if (p.snapshots.length > 0) {
      const last = p.snapshots[p.snapshots.length - 1];
      last.lanes.forEach(l => {
        Object.entries(l.vehicles).forEach(([type, count]) => {
          vehicleCounts[type] = (vehicleCounts[type] || 0) + (count as number);
        });
      });
      totalVehicles += last.intersectionSum;
    }
  });

  doc.setFontSize(14);
  doc.text("Executive Summary", 14, 80);
  
  doc.autoTable({
    startY: 85,
    head: [["Metric", "Value"]],
    body: [
      ["Total Unique Vehicles Processed", totalVehicles.toLocaleString()],
      ["Number of Sessions Recorded", data.length.toString()],
      ["Primary Vehicle Classification", Object.entries(vehicleCounts).sort((a,b) => b[1]-a[1])[0]?.[0] || "N/A"]
    ],
    theme: 'striped',
    headStyles: { fillStyle: 'dark', fillColor: [78, 98, 144] }
  });

  // Vehicle Breakdown Table
  doc.addPage();
  doc.text("Vehicle Classification Breakdown", 14, 22);
  
  const vehicleRows = Object.entries(vehicleCounts).sort((a,b) => b[1]-a[1]).map(([type, count]) => [
    type.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
    count.toLocaleString(),
    `${((count / totalVehicles) * 100).toFixed(1)}%`
  ]);

  doc.autoTable({
    startY: 30,
    head: [["Vehicle Type", "Count", "Percentage Share"]],
    body: vehicleRows,
    theme: 'grid',
    headStyles: { fillColor: [78, 98, 144] }
  });

  // Incident Summary if it was an incident report summary
  if (metadata.type.includes("Incident")) {
    // In a real app, we'd fetch actual incidents here or pass them in
    doc.addPage();
    doc.text("Incident Summary", 14, 22);
    doc.text("Data extracted from incident_reports collection.", 14, 30);
    // Placeholder for actual incident data
  }

  // Certification Block for Certified Traffic Log
  if (metadata.certifiedBy) {
    const finalY = (doc as any).lastAutoTable.finalY + 30;
    doc.setDrawColor(203, 213, 225);
    doc.line(14, finalY, 100, finalY);
    doc.setFontSize(10);
    doc.text("Certified Correct:", 14, finalY + 5);
    doc.setFontSize(12);
    doc.text(metadata.certifiedBy, 14, finalY + 12);
    doc.setFontSize(10);
    doc.text("Officer-in-Charge, STAP Hub Operations", 14, finalY + 17);
    doc.text(`Date of Certification: ${metadata.certifiedAt || new Date().toLocaleDateString()}`, 14, finalY + 22);
    
    // Stamp effect
    doc.setDrawColor(220, 38, 38);
    doc.setLineWidth(0.5);
    doc.rect(pageWidth - 70, finalY, 56, 25);
    doc.setTextColor(220, 38, 38);
    doc.setFontSize(14);
    doc.text("CERTIFIED", pageWidth - 42, finalY + 12, { align: "center" });
    doc.setFontSize(8);
    doc.text("STAP OFFICIAL DOCUMENT", pageWidth - 42, finalY + 18, { align: "center" });
  }

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `STAP-HUB • Page ${i} of ${totalPages} • Ref: ${metadata.refNumber || 'STAP-' + Math.random().toString(36).substr(2, 9).toUpperCase()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  return doc;
};
